# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  publish = "_site/"
  command = "./build.sh"

# Production context: all deploys from the Production branch set in your site's 
# deploy contexts will inherit these settings.
[context.production]
  publish = "_site/"
  command = "JEKYLL_ENV=production ./build.sh"


# Deploy Preview context: all deploys resulting from a pull/merge request will 
# inherit these settings.
[context.deploy-preview]
  publish = "_site/"
  command = "JEKYLL_ENV=develop ./build.sh"

# Branch Deploy context: all deploys that are not from a pull/merge request or 
# from the Production branch will inherit these settings.
[context.branch-deploy]
  publish = "_site/"
  command = "JEKYLL_ENV=develop ./build.sh"

[context.april-fools]
  command = "JEKYLL_ENV=ducks ./build.sh"