# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  publish = "_site/"
  command = "./build.sh"

# Production context: all deploys from the Production branch set in your site's
# deploy contexts will inherit these settings.
[context.production]
  publish = "_site/"
  command = "JEKYLL_ENV=production ./build.sh"


# Deploy Preview context: all deploys resulting from a pull/merge request will
# inherit these settings.
[context.deploy-preview]
  publish = "_site/"
  command = "JEKYLL_ENV=develop ./build.sh"

# Branch Deploy context: all deploys that are not from a pull/merge request or
# from the Production branch will inherit these settings.
[context.branch-deploy]
  publish = "_site/"
  command = "JEKYLL_ENV=develop ./build.sh"

# REDIRECTS. Precede each block with `[[redirects]]`,
# and leave a blank line in between each block.
# Netlify doc on redirects:
# https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file

[[redirects]]
  from = "https://logz-docs.netlify.com/*"
  to = "https://docs.logz.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/access-and-authentication/*"
  to = "/user-guide/tokens/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/shippers/*"
  to = "/shipping/log-sources/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/active-directory-winserver.html"
  to = "/shipping/security-sources/active-directory-winserver.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/alcide.html"
  to = "/shipping/security-sources/alcide.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/auditd.html"
  to = "/shipping/security-sources/auditd.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/aws-waf.html"
  to = "/shipping/security-sources/aws-waf.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/azure-activity-logs.html"
  to = "/shipping/security-sources/azure-activity-logs.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/bitdefender.html"
  to = "/shipping/security-sources/bitdefender.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/check-point.html"
  to = "/shipping/security-sources/check-point.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/cisco-asa.html"
  to = "/shipping/security-sources/cisco-asa.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/cisco-meraki.html"
  to = "/shipping/security-sources/cisco-meraki.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/cloudtrail.html"
  to = "/shipping/security-sources/cloudtrail.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/eset.html"
  to = "/shipping/security-sources/eset.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/fail2ban.html"
  to = "/shipping/security-sources/fail2ban.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/falco.html"
  to = "/shipping/security-sources/falco.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/fortigate.html"
  to = "/shipping/security-sources/fortigate.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/gsuite.html"
  to = "/shipping/security-sources/gsuite.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/guardduty.html"
  to = "/shipping/security-sources/guardduty.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/hashicorp-vault.html"
  to = "/shipping/security-sources/hashicorp-vault.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/juniper-srx.html"
  to = "/shipping/security-sources/juniper-srx.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/mcafee-epolicy-orchestrator.html"
  to = "/shipping/security-sources/mcafee-epolicy-orchestrator.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/microsoft-graph.html"
  to = "/shipping/security-sources/microsoft-graph.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/modsecurity.html"
  to = "/shipping/security-sources/modsecurity.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/nginx.html"
  to = "/shipping/security-sources/nginx.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/okta.html"
  to = "/shipping/security-sources/okta.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/openvas.html"
  to = "/shipping/security-sources/openvas.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/ossec.html"
  to = "/shipping/security-sources/ossec.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/palo-alto-networks.html"
  to = "/shipping/security-sources/palo-alto-networks.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/sentinelone.html"
  to = "/shipping/security-sources/sentinelone.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/sonicwall.html"
  to = "/shipping/security-sources/sonicwall.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/sophos.html"
  to = "/shipping/security-sources/sophos.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/stormshield.html"
  to = "/shipping/security-sources/stormshield.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/sysmon.html"
  to = "/shipping/security-sources/sysmon.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/trendmicro.html"
  to = "/shipping/security-sources/trendmicro.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/wazuh.html"
  to = "/shipping/security-sources/wazuh.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/windows-defender.html"
  to = "/shipping/security-sources/windows-defender.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/zeek.html"
  to = "/shipping/security-sources/zeek.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/filebeat-for-windows.html"
  to = "/shipping/log-sources/filebeat.html"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/infrastructure-monitoring/custom-metrics"
  to = "/shipping/metrics-sources/custom-metrics.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/p8s-sources/*"
  to = "/shipping/prometheus-sources/:splat"
  status = 301
  force = true
 
[[redirects]]
  from = "/user-guide/infrastructure-monitoring/p8s-*"
  to = "/user-guide/infrastructure-monitoring/prometheus-:splat"
  status = 301
  force = true  

[[redirects]]
  from = "/shipping/p8s-sources/*"
  to = "/shipping/prometheus-sources/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/infrastructure-monitoring/grafana*"   
  to = "/user-guide/infrastructure-monitoring/metrics:splat"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/infrastructure-monitoring/configure-grafana*"   
  to = "/user-guide/infrastructure-monitoring/configure-metrics:splat"
  status = 301
  force = true

