version: "3"
services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  #Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-logzio
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./config.yaml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "9411"   # Zipkin receiver
      - "55680:55679" # zpages extension
    depends_on:
      - jaeger
      - zipkin

  # Expose the frontend on http://localhost:8081
  hotrod:
    image: jaegertracing/example-hotrod:latest
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    environment:
      JAEGER_ENDPOINT: http://otel-collector:14268/api/traces
    depends_on:
      - otel-collector
