---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: monitoring
  name: event-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    namespace: monitoring
    name: event-exporter
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    logLevel: ${EXPORTER_LOG_LEVEL}
    logFormat: json
    route:
      routes:
        - match:
            - receiver: "logzio"
    receivers:
      - name: "logzio"
        webhook:
          endpoint: https://${LOGZIO_LOGS_LISTENER_HOST}:8071/?token=${LOGZIO_LOGS_SHIPPING_TOKEN}&type=k8s-events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: event-exporter
        version: v1
    spec:
      serviceAccountName: event-exporter
      containers:
        - name: event-exporter
          image: ghcr.io/opsgenie/kubernetes-event-exporter:v0.11
          imagePullPolicy: IfNotPresent
          args:
            - -conf=/data/config.yaml
          volumeMounts:
            - mountPath: /data
              name: cfg
          env:
          - name: LOGZIO_LOGS_SHIPPING_TOKEN
            valueFrom:
              secretKeyRef:
                name: logzio-events-secret
                key: logzio-log-shipping-token
          - name: LOGZIO_LOGS_LISTENER_HOST
            valueFrom:
              secretKeyRef:
                name: logzio-events-secret
                key: logzio-log-listener
          - name: EXPORTER_LOG_LEVEL
            value: info
      volumes:
        - name: cfg
          configMap:
            name: event-exporter-cfg
  selector:
    matchLabels:
      app: event-exporter
      version: v1
---
