############################# Input #####################################
filebeat.inputs:
- type: log
  paths:
  - /path/to/log/file.log

  fields:
    # For JSON logs, set to `json`. For plain log lines, set to `plain`
    logzio_codec: plain

    # Your Logz.io account token. You can find your token at
    #  https://app.logz.io/#/dashboard/settings/manage-accounts
    token: LOGZIO-TOKEN

    # Logz.io uses log type to parse your logs. Logs of the same type are
    #  parsed the same way. For more information, see
    #  https://docs.logz.io/user-guide/log-shipping/built-in-log-types.html
    #
    # For custom parsing you can:
    #  - Configure Logstash in your system
    #  - Use the Data Parsing wizard (https://app.logz.io/#/dashboard/data-parsing/step1)
    #  - Get help from the Support team (email help@logz.io)
    type: LOG-TYPE

  # fields_under_root must be set to `true`
  fields_under_root: true
  encoding: utf-8
  ignore_older: 3h

registry_file: /var/lib/filebeat/registry

############################# Output ##########################################
output:
  logstash:
    # If your Logz.io login URL is app-eu.logz.io, then change hosts to
    #  `listener-eu.logz.io:5015`
    hosts: ["listener.logz.io:5015"]

    ssl:
      # For Linux, download the Logz.io public certificate to this folder.
      # For Windows, replace the filepath with the certificate's location.
      certificate_authorities: ['/etc/pki/tls/certs/COMODORSADomainValidationSecureServerCA.crt']